name: FasterRCNN  # Model type
num_classes: 5  # Number of classes

backbone:
  _target_: torchvision.models.mobilenet_v2  # Use torchvision's MobileNetV2
  pretrained: True  # Whether to use a pretrained backbone

training:
epochs: 10
learning_rate: 0.001

# Optimizer configuration
optimizer:
  _target_: torch.optim.Adam  # Specify the optimizer class
  lr: 0.001  # Learning rate (can be overridden at runtime)

# Loss function configuration is default as pytorch torchvision implementation